# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'web-container' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for web-container
  pod 'SnapKit', '~> 5.0.0'
  pod 'Log'
  pod 'RxSwift'
  pod 'RxMediaPicker', :git => 'https://github.com/cythb/RxMediaPicker.git'
  pod 'swiftScan', :git => 'https://github.com/MxABC/swiftScan.git'
  pod 'Zip'
  pod 'RxAlamofire'

end
